// worldcup-data.js - FIFA World Cup 2026 Data Module
// 48 teams, 12 groups, 104 matches
// June 11 - July 19, 2026 | USA, Canada, Mexico

const WC2026 = {
  info: {
    name: 'FIFA World Cup 2026',
    nameVi: 'Giải Vô Địch Bóng Đá Thế Giới 2026',
    startDate: '2026-06-11',
    endDate: '2026-07-19',
    hosts: ['USA', 'Canada', 'Mexico'],
    hostsVi: ['Mỹ', 'Canada', 'Mexico'],
    teams: 48,
    groups: 12,
    matches: 104,
    format: '48 đội, 12 bảng, 104 trận',
    slogan: 'We Are 26',
  },

  dates: {
    start: '2026-06-11',
    groupEnd: '2026-06-28',
    r32Start: '2026-06-29',
    r16Start: '2026-07-01',
    qfStart: '2026-07-04',
    sfStart: '2026-07-08',
    thirdPlace: '2026-07-18',
    final: '2026-07-19',
  },

  groups: {
    A: { teams: ['USA', 'Morocco', 'Scotland', 'TBD'], venue: 'SoFi Stadium, Los Angeles', venueVi: 'SoFi Stadium, Los Angeles' },
    B: { teams: ['Mexico', 'Nigeria', 'Sweden', 'TBD'], venue: 'Estadio Azteca, Mexico City', venueVi: 'Estadio Azteca, Mexico City' },
    C: { teams: ['Canada', 'Senegal', 'Serbia', 'TBD'], venue: 'BMO Field, Toronto', venueVi: 'BMO Field, Toronto' },
    D: { teams: ['Brazil', 'Japan', 'Costa Rica', 'TBD'], venue: 'Hard Rock Stadium, Miami', venueVi: 'Hard Rock Stadium, Miami' },
    E: { teams: ['Argentina', 'Australia', 'Ecuador', 'TBD'], venue: 'MetLife Stadium, New York', venueVi: 'MetLife Stadium, New York' },
    F: { teams: ['France', 'South Korea', 'Saudi Arabia', 'TBD'], venue: 'AT&T Stadium, Dallas', venueVi: 'AT&T Stadium, Dallas' },
    G: { teams: ['England', 'Iran', 'Panama', 'TBD'], venue: 'NRG Stadium, Houston', venueVi: 'NRG Stadium, Houston' },
    H: { teams: ['Spain', 'Poland', 'Tunisia', 'TBD'], venue: 'Mercedes-Benz Stadium, Atlanta', venueVi: 'Mercedes-Benz Stadium, Atlanta' },
    I: { teams: ['Germany', 'Ghana', 'Uruguay', 'TBD'], venue: 'Lincoln Financial Field, Philadelphia', venueVi: 'Lincoln Financial Field, Philadelphia' },
    J: { teams: ['Portugal', 'Cameroon', 'Paraguay', 'TBD'], venue: 'Lumen Field, Seattle', venueVi: 'Lumen Field, Seattle' },
    K: { teams: ['Netherlands', 'Croatia', 'Qatar', 'TBD'], venue: 'Gillette Stadium, Boston', venueVi: 'Gillette Stadium, Boston' },
    L: { teams: ['Italy', 'Colombia', 'Denmark', 'TBD'], venue: 'BC Place, Vancouver', venueVi: 'BC Place, Vancouver' },
  },

  venues: [
    { name: 'MetLife Stadium', city: 'New York/New Jersey', capacity: 82500, country: 'USA', countryVi: 'Mỹ', slug: 'metlife-stadium', description: 'Sân vận động lớn nhất World Cup 2026, nơi diễn ra trận chung kết. Nằm ở East Rutherford, New Jersey, phục vụ cả New York Giants và New York Jets.' },
    { name: 'SoFi Stadium', city: 'Los Angeles', capacity: 70240, country: 'USA', countryVi: 'Mỹ', slug: 'sofi-stadium', description: 'Sân vận động hiện đại nhất thế giới tại Inglewood, California. Trị giá 5.5 tỷ USD, sân nhà của LA Rams và LA Chargers.' },
    { name: 'AT&T Stadium', city: 'Dallas', capacity: 80000, country: 'USA', countryVi: 'Mỹ', slug: 'att-stadium', description: 'Sân nhà của Dallas Cowboys với màn hình video khổng lồ đặc trưng. Nằm tại Arlington, Texas.' },
    { name: 'Hard Rock Stadium', city: 'Miami', capacity: 64767, country: 'USA', countryVi: 'Mỹ', slug: 'hard-rock-stadium', description: 'Sân nhà của Miami Dolphins tại Miami Gardens, Florida. Đã tổ chức nhiều sự kiện thể thao lớn và Super Bowl.' },
    { name: 'NRG Stadium', city: 'Houston', capacity: 72220, country: 'USA', countryVi: 'Mỹ', slug: 'nrg-stadium', description: 'Sân vận động có mái che retractable tại Houston, Texas. Sân nhà của Houston Texans.' },
    { name: 'Mercedes-Benz Stadium', city: 'Atlanta', capacity: 71000, country: 'USA', countryVi: 'Mỹ', slug: 'mercedes-benz-stadium', description: 'Sân vận động với thiết kế mái che độc đáo hình cánh hoa tại Atlanta, Georgia. Sân nhà của Atlanta Falcons và Atlanta United.' },
    { name: 'Lincoln Financial Field', city: 'Philadelphia', capacity: 69176, country: 'USA', countryVi: 'Mỹ', slug: 'lincoln-financial-field', description: 'Sân nhà của Philadelphia Eagles tại South Philadelphia. Nổi tiếng với bầu không khí cuồng nhiệt.' },
    { name: 'Lumen Field', city: 'Seattle', capacity: 68740, country: 'USA', countryVi: 'Mỹ', slug: 'lumen-field', description: 'Sân nhà của Seattle Seahawks và Seattle Sounders FC. Nổi tiếng là một trong những sân ồn ào nhất NFL.' },
    { name: 'Gillette Stadium', city: 'Boston/Foxborough', capacity: 65878, country: 'USA', countryVi: 'Mỹ', slug: 'gillette-stadium', description: 'Sân nhà của New England Patriots và New England Revolution tại Foxborough, Massachusetts.' },
    { name: 'Levi\'s Stadium', city: 'San Francisco/Bay Area', capacity: 68500, country: 'USA', countryVi: 'Mỹ', slug: 'levis-stadium', description: 'Sân nhà của San Francisco 49ers tại Santa Clara, California. Sân vận động xanh với nhiều tấm pin năng lượng mặt trời.' },
    { name: 'BMO Field', city: 'Toronto', capacity: 45736, country: 'Canada', countryVi: 'Canada', slug: 'bmo-field', description: 'Sân vận động bóng đá chuyên dụng tại Toronto, Ontario. Sân nhà của Toronto FC trong MLS.' },
    { name: 'BC Place', city: 'Vancouver', capacity: 54500, country: 'Canada', countryVi: 'Canada', slug: 'bc-place', description: 'Sân vận động đa năng tại Vancouver, British Columbia. Có mái che retractable lớn nhất thế giới.' },
    { name: 'Estadio Azteca', city: 'Mexico City', capacity: 87523, country: 'Mexico', countryVi: 'Mexico', slug: 'estadio-azteca', description: 'Sân vận động huyền thoại, từng tổ chức 2 trận chung kết World Cup (1970, 1986). Nơi Maradona ghi bàn thắng "Bàn tay Chúa". Sức chứa lớn nhất World Cup 2026.' },
    { name: 'Estadio BBVA', city: 'Monterrey', capacity: 53500, country: 'Mexico', countryVi: 'Mexico', slug: 'estadio-bbva', description: 'Sân nhà của CF Monterrey, được khánh thành năm 2015. Thiết kế hiện đại với hình dáng độc đáo.' },
    { name: 'Estadio Akron', city: 'Guadalajara', capacity: 49850, country: 'Mexico', countryVi: 'Mexico', slug: 'estadio-akron', description: 'Sân nhà của CD Guadalajara (Chivas), sân vận động bóng đá chuyên dụng lớn nhất Mexico.' },
    { name: 'Arrowhead Stadium', city: 'Kansas City', capacity: 76416, country: 'USA', countryVi: 'Mỹ', slug: 'arrowhead-stadium', description: 'Sân nhà của Kansas City Chiefs, từng giữ kỷ lục Guinness về sân ồn nhất thế giới (142.2 dB).' },
  ],

  teamProfiles: {
    'brazil': { name: 'Brazil', nameVi: 'Brazil', fifaRank: 1, confederation: 'CONMEBOL', wcAppearances: 22, wcTitles: 5, titleYears: '1958, 1962, 1970, 1994, 2002', coach: 'Dorival Júnior', keyPlayers: ['Vinícius Jr', 'Rodrygo', 'Endrick'], flag: '\u{1F1E7}\u{1F1F7}', group: 'D', slug: 'brazil',
      descVi: 'Brazil là đội tuyển thành công nhất lịch sử World Cup với 5 lần vô địch. "Selecao" luôn là ứng viên hàng đầu cho mọi giải đấu với lối chơi samba quyến rũ đặc trưng. Tại World Cup 2026, thế hệ vàng mới với Vinícius Jr, Rodrygo và thần đồng Endrick sẽ mang theo khát vọng giành danh hiệu thứ 6 trong lịch sử.',
    },
    'argentina': { name: 'Argentina', nameVi: 'Argentina', fifaRank: 2, confederation: 'CONMEBOL', wcAppearances: 18, wcTitles: 3, titleYears: '1978, 1986, 2022', coach: 'Lionel Scaloni', keyPlayers: ['Lionel Messi', 'Julián Álvarez', 'Enzo Fernández'], flag: '\u{1F1E6}\u{1F1F7}', group: 'E', slug: 'argentina',
      descVi: 'Argentina là đương kim vô địch World Cup 2022 tại Qatar. Dưới sự dẫn dắt của Lionel Scaloni và huyền thoại Lionel Messi, "Albiceleste" đang ở đỉnh cao phong độ. World Cup 2026 có thể là giải đấu cuối cùng của Messi, và cả đội sẽ chiến đấu để bảo vệ ngôi vương.',
    },
    'france': { name: 'France', nameVi: 'Pháp', fifaRank: 3, confederation: 'UEFA', wcAppearances: 16, wcTitles: 2, titleYears: '1998, 2018', coach: 'Didier Deschamps', keyPlayers: ['Kylian Mbappé', 'Antoine Griezmann', 'Aurélien Tchouaméni'], flag: '\u{1F1EB}\u{1F1F7}', group: 'F', slug: 'france',
      descVi: 'Pháp là á quân World Cup 2022 và vô địch năm 2018. "Les Bleus" sở hữu đội hình đáng sợ với Kylian Mbappé - một trong những cầu thủ nhanh nhất thế giới. HLV Didier Deschamps đã xây dựng một tập thể mạnh mẽ, sẵn sàng tranh đoạt ngôi vương tại Bắc Mỹ.',
    },
    'england': { name: 'England', nameVi: 'Anh', fifaRank: 4, confederation: 'UEFA', wcAppearances: 16, wcTitles: 1, titleYears: '1966', coach: 'Thomas Tuchel', keyPlayers: ['Jude Bellingham', 'Bukayo Saka', 'Phil Foden'], flag: '\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}', group: 'G', slug: 'england',
      descVi: 'Anh là đội tuyển luôn được kỳ vọng nhưng chưa vô địch World Cup kể từ năm 1966. Với thế hệ tài năng Jude Bellingham, Bukayo Saka, Phil Foden, "Tam Sư" đang sở hữu lứa cầu thủ xuất sắc nhất trong nhiều thập kỷ. World Cup 2026 có thể là cơ hội vàng để chấm dứt cơn khát danh hiệu.',
    },
    'germany': { name: 'Germany', nameVi: 'Đức', fifaRank: 5, confederation: 'UEFA', wcAppearances: 20, wcTitles: 4, titleYears: '1954, 1974, 1990, 2014', coach: 'Julian Nagelsmann', keyPlayers: ['Jamal Musiala', 'Florian Wirtz', 'Kai Havertz'], flag: '\u{1F1E9}\u{1F1EA}', group: 'I', slug: 'germany',
      descVi: 'Đức là đội tuyển có truyền thống mạnh mẽ với 4 lần vô địch World Cup. Sau giai đoạn khó khăn, "Die Mannschaft" đang tái sinh với thế hệ trẻ tài năng do Julian Nagelsmann dẫn dắt. Jamal Musiala và Florian Wirtz được xem là tương lai của bóng đá Đức.',
    },
    'spain': { name: 'Spain', nameVi: 'Tây Ban Nha', fifaRank: 6, confederation: 'UEFA', wcAppearances: 16, wcTitles: 1, titleYears: '2010', coach: 'Luis de la Fuente', keyPlayers: ['Lamine Yamal', 'Pedri', 'Rodri'], flag: '\u{1F1EA}\u{1F1F8}', group: 'H', slug: 'spain',
      descVi: 'Tây Ban Nha vô địch Euro 2024 và World Cup 2010 với lối chơi tiki-taka huyền thoại. Thần đồng Lamine Yamal, chỉ mới 18 tuổi tại World Cup 2026, cùng Pedri và Rodri tạo nên một đội hình trẻ trung và đầy sáng tạo. "La Roja" là ứng viên nặng ký cho chức vô địch.',
    },
    'portugal': { name: 'Portugal', nameVi: 'Bồ Đào Nha', fifaRank: 7, confederation: 'UEFA', wcAppearances: 8, wcTitles: 0, titleYears: '', coach: 'Roberto Martínez', keyPlayers: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Rafael Leão'], flag: '\u{1F1F5}\u{1F1F9}', group: 'J', slug: 'portugal',
      descVi: 'Bồ Đào Nha mang theo huyền thoại Cristiano Ronaldo, người có thể tham dự World Cup cuối cùng ở tuổi 41. "Selecao das Quinas" kết hợp kinh nghiệm của CR7 với tài năng trẻ Rafael Leão và sự sáng tạo của Bruno Fernandes. Liệu Ronaldo có thể hoàn thành giấc mơ World Cup?',
    },
    'japan': { name: 'Japan', nameVi: 'Nhật Bản', fifaRank: 15, confederation: 'AFC', wcAppearances: 7, wcTitles: 0, titleYears: '', coach: 'Hajime Moriyasu', keyPlayers: ['Takefusa Kubo', 'Kaoru Mitoma', 'Wataru Endo'], flag: '\u{1F1EF}\u{1F1F5}', group: 'D', slug: 'japan',
      descVi: 'Nhật Bản là đội bóng số 1 châu Á với phong độ ấn tượng trong vòng loại. "Samurai Xanh" đã đánh bại cả Đức và Tây Ban Nha tại World Cup 2022 và đang nhắm đến mục tiêu vào tứ kết hoặc xa hơn. Đội hình có nhiều cầu thủ thi đấu tại các giải đấu hàng đầu châu Âu.',
    },
    'south-korea': { name: 'South Korea', nameVi: 'Hàn Quốc', fifaRank: 22, confederation: 'AFC', wcAppearances: 11, wcTitles: 0, titleYears: '', coach: 'Hong Myung-bo', keyPlayers: ['Son Heung-min', 'Kim Min-jae', 'Lee Kang-in'], flag: '\u{1F1F0}\u{1F1F7}', group: 'F', slug: 'south-korea',
      descVi: 'Hàn Quốc với đội trưởng Son Heung-min luôn là đại diện đáng gờm của châu Á. "Chiến binh Taegeuk" từng tạo kỳ tích hạng 4 World Cup 2002 trên sân nhà và luôn thi đấu bằng tinh thần chiến đấu mãnh liệt. World Cup 2026 có thể là giải đấu cuối cùng của Son Heung-min.',
    },
    'usa': { name: 'United States', nameVi: 'Mỹ', fifaRank: 11, confederation: 'CONCACAF', wcAppearances: 11, wcTitles: 0, titleYears: '', coach: 'Mauricio Pochettino', keyPlayers: ['Christian Pulisic', 'Gio Reyna', 'Yunus Musah'], flag: '\u{1F1FA}\u{1F1F8}', group: 'A', slug: 'usa',
      descVi: 'Mỹ là một trong ba nước chủ nhà World Cup 2026. Với lợi thế sân nhà và thế hệ tài năng nhất lịch sử bóng đá Mỹ, đội tuyển dưới sự dẫn dắt của Mauricio Pochettino đặt mục tiêu đi sâu vào giải. Christian Pulisic là ngôi sao sáng nhất, thi đấu cho AC Milan tại Serie A.',
    },
    'mexico': { name: 'Mexico', nameVi: 'Mexico', fifaRank: 14, confederation: 'CONCACAF', wcAppearances: 17, wcTitles: 0, titleYears: '', coach: 'Javier Aguirre', keyPlayers: ['Hirving Lozano', 'Edson Álvarez', 'Santiago Giménez'], flag: '\u{1F1F2}\u{1F1FD}', group: 'B', slug: 'mexico',
      descVi: 'Mexico là nước đồng chủ nhà và có truyền thống bóng đá lâu đời. "El Tri" đã tham dự World Cup 17 lần, nhiều nhất trong khu vực CONCACAF. Với sự hỗ trợ của khán giả nhà và sân Estadio Azteca huyền thoại, Mexico hy vọng phá kỷ lục "vòng 16 đội" và tiến xa hơn.',
    },
    'netherlands': { name: 'Netherlands', nameVi: 'Hà Lan', fifaRank: 8, confederation: 'UEFA', wcAppearances: 11, wcTitles: 0, titleYears: '', coach: 'Ronald Koeman', keyPlayers: ['Virgil van Dijk', 'Cody Gakpo', 'Xavi Simons'], flag: '\u{1F1F3}\u{1F1F1}', group: 'K', slug: 'netherlands',
      descVi: 'Hà Lan nổi tiếng với "Bóng đá tổng lực" và 3 lần vào chung kết World Cup nhưng chưa bao giờ vô địch. Đội hình hiện tại với Virgil van Dijk, Cody Gakpo và thần đồng Xavi Simons đang rất mạnh. "Cơn lốc Cam" luôn là đội bóng hấp dẫn với lối chơi tấn công đẹp mắt.',
    },
    'italy': { name: 'Italy', nameVi: 'Ý', fifaRank: 9, confederation: 'UEFA', wcAppearances: 18, wcTitles: 4, titleYears: '1934, 1938, 1982, 2006', coach: 'Luciano Spalletti', keyPlayers: ['Gianluigi Donnarumma', 'Federico Chiesa', 'Nicolò Barella'], flag: '\u{1F1EE}\u{1F1F9}', group: 'L', slug: 'italy',
      descVi: 'Ý là nhà vô địch Euro 2020 và có 4 lần vô địch World Cup. Sau nỗi đau không vượt qua vòng loại World Cup 2018 và 2022, "Azzurri" quyết tâm trở lại sân khấu lớn nhất. HLV Luciano Spalletti đang xây dựng lại đội tuyển với sự pha trộn giữa kinh nghiệm và sức trẻ.',
    },
    'croatia': { name: 'Croatia', nameVi: 'Croatia', fifaRank: 10, confederation: 'UEFA', wcAppearances: 6, wcTitles: 0, titleYears: '', coach: 'Zlatko Dalić', keyPlayers: ['Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić'], flag: '\u{1F1ED}\u{1F1F7}', group: 'K', slug: 'croatia',
      descVi: 'Croatia liên tục gây bất ngờ tại các World Cup gần đây: á quân 2018, hạng 3 năm 2022. Đội hình kết hợp huyền thoại Luka Modrić (có thể là WC cuối cùng) với thế hệ trẻ tài năng như Joško Gvardiol. Dù là nước nhỏ chỉ 4 triệu dân, Croatia luôn thi đấu ở đẳng cấp cao nhất.',
    },
    'morocco': { name: 'Morocco', nameVi: 'Morocco', fifaRank: 12, confederation: 'CAF', wcAppearances: 6, wcTitles: 0, titleYears: '', coach: 'Walid Regragui', keyPlayers: ['Achraf Hakimi', 'Hakim Ziyech', 'Youssef En-Nesyri'], flag: '\u{1F1F2}\u{1F1E6}', group: 'A', slug: 'morocco',
      descVi: 'Morocco tạo nên câu chuyện cổ tích đẹp nhất World Cup 2022 khi trở thành đội châu Phi đầu tiên vào bán kết. "Sư tử Atlas" với HLV Walid Regragui sở hữu hàng thủ vững chắc cùng lối chơi kỷ luật. Tại World Cup 2026, Morocco sẽ gặp nước chủ nhà Mỹ ngay vòng bảng.',
    },
    'belgium': { name: 'Belgium', nameVi: 'Bỉ', fifaRank: 6, confederation: 'UEFA', wcAppearances: 14, wcTitles: 0, titleYears: '', coach: 'Domenico Tedesco', keyPlayers: ['Kevin De Bruyne', 'Jérémy Doku', 'Romelu Lukaku'], flag: '\u{1F1E7}\u{1F1EA}', group: 'L', slug: 'belgium',
      descVi: 'Bỉ từng đứng số 1 thế giới nhiều năm với thế hệ vàng De Bruyne, Lukaku, Hazard. Dù không giành được danh hiệu lớn, "Quỷ Đỏ" vẫn là đối thủ đáng gờm. World Cup 2026 có thể là cơ hội cuối cùng của thế hệ vàng này.',
    },
  },

  // Sample group stage schedule (first few days, Vietnamese timezone UTC+7)
  schedule: [
    { date: '2026-06-11', timeUTC7: '23:00', home: 'Mexico', away: 'TBD', group: 'B', venue: 'Estadio Azteca', stage: 'Vòng bảng' },
    { date: '2026-06-12', timeUTC7: '02:00', home: 'USA', away: 'Morocco', group: 'A', venue: 'SoFi Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-12', timeUTC7: '05:00', home: 'Argentina', away: 'TBD', group: 'E', venue: 'MetLife Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-12', timeUTC7: '08:00', home: 'Canada', away: 'TBD', group: 'C', venue: 'BMO Field', stage: 'Vòng bảng' },
    { date: '2026-06-12', timeUTC7: '23:00', home: 'Brazil', away: 'Costa Rica', group: 'D', venue: 'Hard Rock Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-13', timeUTC7: '02:00', home: 'France', away: 'Saudi Arabia', group: 'F', venue: 'AT&T Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-13', timeUTC7: '05:00', home: 'England', away: 'Panama', group: 'G', venue: 'NRG Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-13', timeUTC7: '08:00', home: 'Spain', away: 'Tunisia', group: 'H', venue: 'Mercedes-Benz Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-14', timeUTC7: '02:00', home: 'Germany', away: 'Ghana', group: 'I', venue: 'Lincoln Financial Field', stage: 'Vòng bảng' },
    { date: '2026-06-14', timeUTC7: '05:00', home: 'Portugal', away: 'Paraguay', group: 'J', venue: 'Lumen Field', stage: 'Vòng bảng' },
    { date: '2026-06-14', timeUTC7: '08:00', home: 'Netherlands', away: 'Qatar', group: 'K', venue: 'Gillette Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-15', timeUTC7: '02:00', home: 'Italy', away: 'Denmark', group: 'L', venue: 'BC Place', stage: 'Vòng bảng' },
    { date: '2026-06-15', timeUTC7: '05:00', home: 'Japan', away: 'TBD', group: 'D', venue: 'Hard Rock Stadium', stage: 'Vòng bảng' },
    { date: '2026-06-15', timeUTC7: '08:00', home: 'South Korea', away: 'TBD', group: 'F', venue: 'AT&T Stadium', stage: 'Vòng bảng' },
    // Key knockout dates
    { date: '2026-07-04', timeUTC7: '02:00', home: 'QF1', away: 'QF2', group: null, venue: 'MetLife Stadium', stage: 'Tứ kết' },
    { date: '2026-07-08', timeUTC7: '02:00', home: 'SF1', away: 'SF2', group: null, venue: 'AT&T Stadium', stage: 'Bán kết' },
    { date: '2026-07-18', timeUTC7: '02:00', home: 'L-SF1', away: 'L-SF2', group: null, venue: 'Hard Rock Stadium', stage: 'Tranh hạng 3' },
    { date: '2026-07-19', timeUTC7: '02:00', home: 'W-SF1', away: 'W-SF2', group: null, venue: 'MetLife Stadium', stage: 'Chung kết' },
  ],

  flags: {
    'USA': '\u{1F1FA}\u{1F1F8}', 'Mexico': '\u{1F1F2}\u{1F1FD}', 'Canada': '\u{1F1E8}\u{1F1E6}',
    'Brazil': '\u{1F1E7}\u{1F1F7}', 'Argentina': '\u{1F1E6}\u{1F1F7}', 'France': '\u{1F1EB}\u{1F1F7}',
    'England': '\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}',
    'Spain': '\u{1F1EA}\u{1F1F8}', 'Germany': '\u{1F1E9}\u{1F1EA}', 'Portugal': '\u{1F1F5}\u{1F1F9}',
    'Italy': '\u{1F1EE}\u{1F1F9}', 'Netherlands': '\u{1F1F3}\u{1F1F1}', 'Croatia': '\u{1F1ED}\u{1F1F7}',
    'Japan': '\u{1F1EF}\u{1F1F5}', 'South Korea': '\u{1F1F0}\u{1F1F7}', 'Australia': '\u{1F1E6}\u{1F1FA}',
    'Morocco': '\u{1F1F2}\u{1F1E6}', 'Senegal': '\u{1F1F8}\u{1F1F3}', 'Nigeria': '\u{1F1F3}\u{1F1EC}',
    'Ghana': '\u{1F1EC}\u{1F1ED}', 'Cameroon': '\u{1F1E8}\u{1F1F2}', 'Tunisia': '\u{1F1F9}\u{1F1F3}',
    'Saudi Arabia': '\u{1F1F8}\u{1F1E6}', 'Iran': '\u{1F1EE}\u{1F1F7}', 'Qatar': '\u{1F1F6}\u{1F1E6}',
    'Ecuador': '\u{1F1EA}\u{1F1E8}', 'Uruguay': '\u{1F1FA}\u{1F1FE}', 'Colombia': '\u{1F1E8}\u{1F1F4}',
    'Paraguay': '\u{1F1F5}\u{1F1FE}', 'Costa Rica': '\u{1F1E8}\u{1F1F7}', 'Panama': '\u{1F1F5}\u{1F1E6}',
    'Poland': '\u{1F1F5}\u{1F1F1}', 'Serbia': '\u{1F1F7}\u{1F1F8}', 'Denmark': '\u{1F1E9}\u{1F1F0}',
    'Sweden': '\u{1F1F8}\u{1F1EA}', 'Scotland': '\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}',
    'Belgium': '\u{1F1E7}\u{1F1EA}',
  },

  teamNameVi: {
    'USA': 'Mỹ', 'Mexico': 'Mexico', 'Canada': 'Canada', 'Brazil': 'Brazil', 'Argentina': 'Argentina',
    'France': 'Pháp', 'England': 'Anh', 'Spain': 'Tây Ban Nha', 'Germany': 'Đức', 'Portugal': 'Bồ Đào Nha',
    'Italy': 'Ý', 'Netherlands': 'Hà Lan', 'Croatia': 'Croatia', 'Japan': 'Nhật Bản', 'South Korea': 'Hàn Quốc',
    'Australia': 'Úc', 'Morocco': 'Morocco', 'Senegal': 'Senegal', 'Nigeria': 'Nigeria', 'Ghana': 'Ghana',
    'Cameroon': 'Cameroon', 'Tunisia': 'Tunisia', 'Saudi Arabia': 'Ả Rập Saudi', 'Iran': 'Iran', 'Qatar': 'Qatar',
    'Ecuador': 'Ecuador', 'Uruguay': 'Uruguay', 'Colombia': 'Colombia', 'Paraguay': 'Paraguay', 'Costa Rica': 'Costa Rica',
    'Panama': 'Panama', 'Poland': 'Ba Lan', 'Serbia': 'Serbia', 'Denmark': 'Đan Mạch', 'Sweden': 'Thụy Điển',
    'Scotland': 'Scotland', 'Belgium': 'Bỉ',
  },
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = WC2026;
}
